rules:
  annotation-no-unknown: true
  at-rule-descriptor-no-unknown: true
  at-rule-descriptor-value-no-unknown: true
  at-rule-no-deprecated: true
  at-rule-no-unknown: true
  at-rule-no-vendor-prefix: true
  custom-property-no-missing-var-function: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-property-value-keyword-no-deprecated:
    - true
    - ignoreKeywords:
        - 'break-word'
  declaration-property-value-no-unknown:
    - true
    - propertiesSyntax:
        '-ms-grid-row-align': 'flex-start'
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword:
    - true
    - ignoreFontFamilies:
        - 'a'
  keyframe-block-no-duplicate-selectors: true
  media-feature-name-no-unknown: true
  media-feature-name-value-no-unknown: true
  media-query-no-invalid: true
  named-grid-areas-no-invalid: true
  no-invalid-double-slash-comments: true
  no-invalid-position-at-import-rule: true
  no-irregular-whitespace: true
  property-no-unknown: true
  selector-anb-no-unmatchable: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  syntax-string-no-invalid: true
  media-feature-name-no-vendor-prefix: true
  declaration-property-value-disallowed-list:
    # Matching all custom properties
    /^--.*/:
    # Disallow any value starting with a $ - SCSS variable.
    - '/^\$.*$/'
  selector-no-vendor-prefix:
    - true
    - ignoreSelectors:
        - '::-moz-selection'
